import * as THREE from 'three';
const $=id=>document.getElementById(id);
const error=$('error');
try{start()}catch(e){console.error(e);error.classList.remove('hidden');error.textContent='KANAPE initialization failed\n\n'+(e.stack||e);$('loading').classList.add('done')}
function start(){
const scene=new THREE.Scene();scene.background=new THREE.Color('#aab7a3');scene.fog=new THREE.FogExp2('#aab7a3',.012);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,500);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;$('game').prepend(renderer.domElement);
const mat=(c)=>new THREE.MeshStandardMaterial({color:c,roughness:1,flatShading:true});
const m={ground:mat('#69745b'),concrete:mat('#88897a'),wall:mat('#aaa58e'),roof:mat('#55584b'),wood:mat('#655b46'),metal:mat('#424a42'),yellow:mat('#d9e76f'),skin:mat('#bd9472'),pants:mat('#424c45'),pack:mat('#4d5944'),black:mat('#30362e'),crate:mat('#8a704c'),leaf:[mat('#596a4d'),mat('#748461'),mat('#3f5140')]};
scene.add(new THREE.HemisphereLight('#dce6d1','#555a43',2.1));const sun=new THREE.DirectionalLight('#fff1d4',3.1);sun.position.set(-35,65,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-65;sun.shadow.camera.right=65;sun.shadow.camera.top=65;sun.shadow.camera.bottom=-65;scene.add(sun);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(500,500),m.ground);floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const world=new THREE.Group();scene.add(world);const colliders=[],supplies=[],keys=new Set(),clock=new THREE.Clock(),velocity=new THREE.Vector3();let yaw=.55,pitch=.28,paused=false,stamina=100,health=100,collected=0,vertical=0,grounded=true,phase=0,msgTime=0,pointerLocked=false;
const player=new THREE.Group();player.position.set(0,0,9);scene.add(player);
function mesh(g,material,x,y,z,parent=world,shadow=true){const o=new THREE.Mesh(g,material);o.position.set(x,y,z);o.castShadow=shadow;o.receiveShadow=true;parent.add(o);return o}
function box(x,y,z,sx,sy,sz,material,solid=true){const o=mesh(new THREE.BoxGeometry(sx,sy,sz),material,x,y+sy/2,z);if(solid)colliders.push({minX:x-sx/2,maxX:x+sx/2,minZ:z-sz/2,maxZ:z+sz/2});return o}
const torso=mesh(new THREE.CapsuleGeometry(.31,.57,4,8),m.yellow,0,1.18,0,player);const head=mesh(new THREE.SphereGeometry(.205,10,8),m.skin,0,1.88,0,player);mesh(new THREE.SphereGeometry(.21,8,6,0,Math.PI*2,0,Math.PI*.55),m.black,0,1.96,0,player);mesh(new THREE.BoxGeometry(.35,.45,.2),m.pack,0,1.28,.28,player);
const arms=[],legs=[];for(const s of [-1,1]){arms.push(mesh(new THREE.CapsuleGeometry(.095,.45,3,6),m.yellow,s*.39,1.2,0,player));legs.push(mesh(new THREE.CapsuleGeometry(.115,.43,3,6),m.pants,s*.16,.49,0,player));mesh(new THREE.BoxGeometry(.22,.12,.34),m.black,s*.16,.12,-.07,player)}
// Invisible collision volume is separate from the visible survivor mesh.
const capsule=new THREE.Mesh(new THREE.CylinderGeometry(.34,.34,1.75,8),new THREE.MeshBasicMaterial({visible:false}));capsule.visible=false;player.add(capsule);
const road=mesh(new THREE.PlaneGeometry(9,150),mat('#777967'),1,.012,-26);road.rotation.x=-Math.PI/2;for(let z=-92;z<48;z+=7){const s=mesh(new THREE.PlaneGeometry(.13,2.2),mat('#c0bda1'),1,.025,z);s.rotation.x=-Math.PI/2}
box(-12,0,-8,9,.22,8,m.concrete);box(-16,.22,-8,.28,3.1,8,m.wall);box(-8,.22,-8,.28,3.1,8,m.wall);box(-12,.22,-11.9,8,3.1,.25,m.wall);box(-12,.22,-4.1,2.6,3.1,.25,m.wall);box(-8.8,.22,-4.1,2.1,3.1,.25,m.wall);box(-12,3.4,-8,9.2,.32,8.2,m.roof);box(-12,3.8,-8,9.6,.2,1.1,m.wood,false);box(-12,.25,-4.4,1.2,2.4,.12,m.wood,false);
box(12,0,-12,6,.18,5,m.concrete);box(9.1,.18,-12,.18,2.4,5,m.wood);box(14.9,.18,-12,.18,2.4,5,m.wood);box(12,.18,-14.4,6,2.4,.18,m.wood);box(12,2.6,-12,6.4,.22,5.4,m.roof);box(12,.18,-9.6,1.7,2.4,.18,m.wood);box(14,.18,-9.6,2,2.4,.18,m.wood);
box(-3,0,-2,1.4,1.1,1.4,m.crate);box(5,0,-20,3.2,.65,.45,m.wood);box(6.6,0,-34,.6,1.6,.6,m.metal);box(-6.6,0,-34,.6,1.6,.6,m.metal);
let seed=9173;const rand=()=>{seed=seed*16807%2147483647;return(seed-1)/2147483646};
for(let i=0;i<105;i++){const x=(rand()-.5)*115,z=(rand()-.5)*155;if(Math.abs(x)<18&&z>-20&&z<20||Math.abs(x-1)<7)continue;mesh(new THREE.CylinderGeometry(.1,.2,1.6,5),m.wood,x,.8,z);for(let j=0;j<3;j++)mesh(new THREE.ConeGeometry(1.1-j*.18,1.9-j*.12,5),m.leaf[Math.abs(Math.floor(x+z+j))%3],x,1.8+j*.65,z)}
for(let i=0;i<180;i++){const p=mesh(new THREE.DodecahedronGeometry(.1+rand()*.25,0),m.leaf[i%3],(rand()-.5)*95,.08,(rand()-.5)*120);p.scale.y=.4;p.rotation.set(rand(),rand(),rand())}
function addSupply(x,z){const g=new THREE.Group();g.position.set(x,.5,z);world.add(g);mesh(new THREE.BoxGeometry(.65,.55,.5),m.crate,0,0,0,g);mesh(new THREE.BoxGeometry(.67,.08,.51),m.yellow,0,.04,0,g);const halo=mesh(new THREE.TorusGeometry(.53,.025,4,24),new THREE.MeshBasicMaterial({color:'#d7ef78'}),0,-.17,0,g,false);halo.rotation.x=Math.PI/2;supplies.push({group:g,halo,taken:false,phase:rand()*6.28})}
[[-3,-5],[17,-18],[-21,-23],[8,-39],[24,8]].forEach(p=>addSupply(...p));
function overlaps(x,z,r=.38){if(Math.abs(x)>110||Math.abs(z)>110)return true;return colliders.some(c=>x+r>c.minX&&x-r<c.maxX&&z+r>c.minZ&&z-r<c.maxZ)}
function message(t){$('message').textContent=t;$('message').classList.add('visible');msgTime=2.2}
function interact(){let nearest=null,distance=2.5;for(const s of supplies){if(s.taken)continue;const d=Math.hypot(s.group.position.x-player.position.x,s.group.position.z-player.position.z);if(d<distance){nearest=s;distance=d}}if(!nearest){message('NOTHING WITHIN REACH');return}nearest.taken=true;nearest.group.visible=false;collected++;$('inventory-count').textContent=String(collected).padStart(2,'0');$('objective-count').textContent='SUPPLIES '+collected+' / 5';$('progress').style.width=(collected/5*100)+'%';message(collected===5?'PERIMETER SECURED — OBJECTIVE COMPLETE':'SUPPLIES SECURED  +1');if(collected===5)$('sector').textContent='A1 / SECURED'}
function pause(v){paused=v;$('pause').classList.toggle('hidden',!v);if(v&&document.pointerLockElement)document.exitPointerLock()}
$('resume').addEventListener('click',()=>pause(false));renderer.domElement.addEventListener('click',()=>{if(!paused&&matchMedia('(pointer:fine)').matches&&document.pointerLockElement!==renderer.domElement)renderer.domElement.requestPointerLock?.()});document.addEventListener('pointerlockchange',()=>pointerLocked=document.pointerLockElement===renderer.domElement);document.addEventListener('mousemove',e=>{if(paused||(!pointerLocked&&e.buttons!==2))return;yaw-=e.movementX*.0025;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.002,-.12,.72)});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){pause(!paused);return}if(paused)return;keys.add(e.code);if(e.code==='KeyE'&&!e.repeat)interact();if(e.code==='Space'&&grounded&&!e.repeat){vertical=6.2;grounded=false}});document.addEventListener('keyup',e=>keys.delete(e.code));
let joyId=null,joyX=0,joyY=0;const joystick=$('joystick'),knob=$('knob');joystick.addEventListener('pointerdown',e=>{joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);joyMove(e)});joystick.addEventListener('pointermove',e=>{if(joyId===e.pointerId)joyMove(e)});function joyMove(e){const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,max=r.width*.31,len=Math.hypot(dx,dy),s=len>max?max/len:1;joyX=dx*s/max;joyY=dy*s/max;knob.style.transform='translate('+dx*s+'px,'+dy*s+'px)'}function joyEnd(e){if(joyId!==e.pointerId)return;joyId=null;joyX=joyY=0;knob.style.transform=''}joystick.addEventListener('pointerup',joyEnd);joystick.addEventListener('pointercancel',joyEnd);
$('jump-button').addEventListener('pointerdown',e=>{e.preventDefault();if(grounded){vertical=6.2;grounded=false}});$('interact-button').addEventListener('pointerdown',e=>{e.preventDefault();interact()});
let lookId=null,lx=0,ly=0;renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'){lookId=e.pointerId;lx=e.clientX;ly=e.clientY}});renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerType!=='touch'||lookId!==e.pointerId)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;if(e.clientX>innerWidth*.38){yaw-=dx*.006;pitch=THREE.MathUtils.clamp(pitch-dy*.004,-.12,.72)}});const endLook=e=>{if(lookId===e.pointerId)lookId=null};renderer.domElement.addEventListener('pointerup',endLook);renderer.domElement.addEventListener('pointercancel',endLook);
const target=new THREE.Vector3(),desired=new THREE.Vector3();function update(dt,time){if(paused)return;const f=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-joyY,s=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joyX;const input=new THREE.Vector2(s,f);if(input.lengthSq()>1)input.normalize();const moving=input.lengthSq()>.01,sprinting=moving&&(keys.has('ShiftLeft')||keys.has('ShiftRight'))&&stamina>1;stamina=sprinting?Math.max(0,stamina-25*dt):Math.min(100,stamina+15*dt);const speed=sprinting?7.3:4.1,sin=Math.sin(yaw),cos=Math.cos(yaw),dx=input.x*cos-input.y*sin,dz=input.x*sin+input.y*cos;velocity.x=THREE.MathUtils.damp(velocity.x,dx*speed,moving?18:14,dt);velocity.z=THREE.MathUtils.damp(velocity.z,dz*speed,moving?18:14,dt);const nx=player.position.x+velocity.x*dt,nz=player.position.z+velocity.z*dt;if(!overlaps(nx,player.position.z))player.position.x=nx;else velocity.x=0;if(!overlaps(player.position.x,nz))player.position.z=nz;else velocity.z=0;vertical-=17*dt;player.position.y+=vertical*dt;if(player.position.y<=0){player.position.y=0;vertical=0;grounded=true}if(moving){const angle=Math.atan2(dx,dz),delta=(angle-player.rotation.y+Math.PI*3)%(Math.PI*2)-Math.PI;player.rotation.y+=delta*Math.min(1,dt*9);phase+=dt*(sprinting?13:8)}const swing=moving&&grounded?Math.sin(phase)*(sprinting?.72:.48):0;legs[0].rotation.x=swing;legs[1].rotation.x=-swing;arms[0].rotation.x=-swing*.7;arms[1].rotation.x=swing*.7;torso.position.y=1.18+(moving&&grounded?Math.abs(Math.sin(phase*2))*.035:0);
const h=Math.cos(pitch)*6.2;desired.set(player.position.x+Math.sin(yaw)*h,Math.max(.55,player.position.y+1.7+Math.sin(pitch)*6.2),player.position.z+Math.cos(yaw)*h);camera.position.lerp(desired,.14);target.set(player.position.x,player.position.y+1.2,player.position.z);camera.lookAt(target);
let near=false;for(const item of supplies){if(item.taken)continue;item.group.position.y=.5+Math.sin(time*1.8+item.phase)*.08;item.halo.rotation.z=time*.6;if(Math.hypot(item.group.position.x-player.position.x,item.group.position.z-player.position.z)<2.5)near=true}$('interaction').classList.toggle('hidden',!near);$('stamina-bar').style.width=stamina+'%';$('stamina-value').textContent=String(Math.round(stamina)).padStart(3,'0');$('health-bar').style.width=health+'%';$('health-value').textContent=String(health).padStart(3,'0');if(msgTime>0){msgTime-=dt;if(msgTime<=0)$('message').classList.remove('visible')}$('sector').textContent=(player.position.x<0?'A':'B')+(Math.floor(Math.abs(player.position.z)/25)+1)+' / LOWLAND'}
camera.position.set(5,4,15);camera.lookAt(player.position.x,1.2,player.position.z);let elapsed=0;function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.04);elapsed+=dt;update(dt,elapsed);renderer.render(scene,camera)}frame();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.8))});setTimeout(()=>$('loading').classList.add('done'),350)
}